#pragma once

#define VIAL_KEYBOARD_UID {0x05, 0xE4, 0xA1, 0x7F, 0xDC, 0x87, 0xCB, 0x2A}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define MATRIX_COLS_DEFAULT 8
#define MATRIX_MSGES_ROW 31

#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define WEAR_LEVELING_BACKING_SIZE (8192 * 2)
#define WEAR_LEVELING_LOGICAL_SIZE 8192
